### ISSUE TITLE
디자인 전반 수정 작업

### ISSUE THREAD

**Issue by AnSuebin** [form-maker/FFF-FE#22]
---
name: 'Issue: ✔Feature '
about: Feature 작업 사항을 입력해주세요.
title: '디자인 전반 수정 작업'
labels: 'design'
assignees: '안수빈'

---

## Description
디자인 전반 수정 작업

## Todo
- [x] 페이지별 글로벌 디자인, Theme 적용
- [x] 메인 페이지 디자인 수정
- [x] 마이 페이지 디자인 수정
- [x] 제작 페이지 디자인 수정
- [x] 통계 페이지 디자인 수정
- [x] 설문 페이지 디자인 수정
